# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
      - image: circleci/postgres:10.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      - run: yarn install
      - run: yarn test
